missions:

  mission_1:
    description: "Template"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/dh/toland.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "hold"]
      - ["uwb", "hold"]
      - ["lrf", "hold"]
      - ["optitrack", "land"]
